### ISSUE TITLE
Hide solutions

### ISSUE THREAD

**Issue by mbtools** [joltdx/abap-advent-2023#1]
Isn't the point of such calendars that the goodies (solutions) are hidden until the day of? 😉

**Comment by joltdx** [comment]
Yes. 👍
I don't really understand though... There are no solutions yet... 🤔
What do you mean?

**Comment by mbtools** [comment]
The description sounds like all solutions are there. It's like all doors are open but nothing inside. Typically you know nothing about the problem until the day of. No worry, the fun will be the same 🥳

**Comment by joltdx** [comment]
Haha, yes, ok, I see what you mean now.
(And sometimes i don't understand the problem even on the actual day... 😅)

Anyway, I updated the readme, with the bonus of a GPT-4 generated poem for it. 😊

Thank you, and have fun!
